addSbtPlugin("com.timushev.sbt"   % "sbt-updates"    % "0.6.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"   % "0.14.6")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"   % "2.6.0")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"   % "0.5.3")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release" % "1.11.2")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"        % "0.4.7")
